version: '3'
networks:
 dev_planestic:

services:
   ud-repository-statistics:
     image: planesticud/ud-repository-statistics:latest
     container_name: ud-repository-statistics
     restart: on-failure
     env_file:
        - .env
     networks:
        - dev_planestic          

networks:
  dev_planestic:
    external: true
